language: c
sudo: required
services:
  - docker
env:
  global:
    - secure: FDx8p7rziiWUbI248oJW3K9CRDNCWTS5VvJ+BNWqj+NetOcEbW/9r3c8SNamx6/Xzkt25imTiHkLN7rB3Q9jVjvej9VbA2v42BQSaQe9kgeGw+2ckyIiRjdm6DU2dLNqp1QCOtKY62PiseCIaIbH1+Fdiydr0IsmpVysqjVzuf8nquzgjQwbCObeFJFDDhwMrM+wlY9DJjMPNgRFA1kWrcBuxBCJh+SkohcizVhvSv4GNDqDhQOfPTQzuknDTyjnUGog9ONPTyu/XIyg873bG6XLNw/d4GI2TCLkCmOasQePPIeigheDD3mri6BisJMOoFGjOQN5nkf9DiEoqJD6yL4krA5oqZeGE8tNzbf/Cu/d8mzdRnA3JZS/XaqbvuB6NYbr9rHCYVryMAadUC7t3KICWyCGCwh5wpNmODNvYKENSgQ2jnLGG8niqz8oiH2qNM5hyoQhoJVpRpKh9j3mZ9El8OmM2Vez5R9z92e/Wtnaaaqqm1IQ5Q8MfZhu+gN6/hQCRI6Oe+M+HL7ij0Hsvi615n89L3uOiyKg6u4V61XMGWQ5tESjlS8YXuYV4LhTtXTN81z5Olmnoap2bsV2hVCpHcNtuodQjUn0+4sEEoDeEyG6LoLNwX7WtIieWoC3nGhZ7u8Jzyfa98fzMIFRyGT/U4jPAuguzz8MdIPs+ZI=
    - secure: ENeGEeW0NyZu+9JsD3iYjcYvutbYfzJOOmXIj+XddbIOev+dQT7mJs1LA/tP/Y8dYrGUsV44WCKJ68lX3u/oTmA56dzlYlESkUiPGMkY7MFDkebL1cJ5Mn62dedmYxnyXTfqjW67LNbd5Dw1g/zfhhfnhUxVwc+TuU/up6XaHmQnlfJGJVt37DjCoYmiNITzv3t4Nx+mTIBdCFaMZabFPf0eDxL4UFrHla5WQ/Vlle1nOz8jtnY56RYrnQ/riT4mUO5F2nrqxa40yK4Rwmm8dIBgerve0EeSMZTdg0iB8yp2pCbGVAMR2l8KoGgkV0NIzXosPh0PhquIapy4fzo3/Hk3sFTGQqyFFR62dVEDf6EX55tNR/LdGUFzz57RclJMbtoUMfLLUMzW6s6KgndJZksMwVdc+PPKRJ3L2Cn16Kc1vjRD4K1KVmE0ki12CCgxGWEzyLMCAzmS21UvseZHwGbwfHwyYoZxVyCSGQvaSEhxU81R53QjlGSfqP01IZIskEmW18LkjYSDrrXPPkKmZFzOGS9xj27mlwO3HvqpYnzT42Aa6NpLIzlAvExBm30XpCAPWu37HAxAiS4EkBjtz0PZci0VaTBezEHBZKyKrKDvDvRnn+FYHpingJqrPPNm4RTKfxizbCs67Y38tvhzF9lgIVjGFSVdxPsUWQHJFEU=

script:
  - ./build.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
